env:
  browser: true
  es2021: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: 2020 # Включает поддержку конструкции import.meta.url
  sourceType: module

rules: 
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
